### ISSUE TITLE
Is there a statement support?

### ISSUE THREAD

**Issue by emelyanovkirill** [daniel-hall/Stylish#23]

**Comment by emelyanovkirill** [comment]
How can I do something like backgroundColor.set(isEnabled ? Color.Red : Color.Grey)?

**Comment by daniel-hall** [comment]
Generally, you would set up styles in a stylesheet called "enabled" and "disabled", something like this:

```
private struct Enabled: Style {
    var propertyStylers: [AnyPropertyStyler] = [backgroundColor.set(value: UIColor.red)]
}

private struct Disabled: Style {
   var propertyStylers: [AnyPropertyStyler] = [backgroundColor.set(value: UIColor.gray)]
}

public class YourStylesheet: Stylesheet {
    public var styles: [String: Style] = ["enabled": Enabled(), "disabled": Disabled()]
}
```

Then in your code, you would apply the style by _name_ instead of using literal values, e.g.

```
@IBOutlet private var button: StyleableUIButton!

func setup() {
    button.styles = button.isEnabled ? "enabled" : "disabled"
}
```

This will apply the right style name to the element instead of the color directly.  And any time you update the definition of the "Enabled" or "Disabled" styles, all elements will get those updates automatically.  Plus, you can set a starting style in the storyboard and see it previewed live in Interface Builder.

Alternatively, you can define those styles in JSON and use a JSONStylesheet, e.g. put this in your stylesheet.json file:

```
{
  "styles": [
    {
      "styleName": "enabled",
      "styleProperties": {
        "backgroundColor": "#FF0000"
      }
    },
    {
      "styleName": "disabled",
      "styleProperties": {
        "backgroundColor": "#CCCCCC"
      }
    }]
}
```

Hope that helps!

**Comment by daniel-hall** [comment]
Closing since there are no further questions...
