### ISSUE TITLE
Storyboards can't find styles all of a sudden

### ISSUE THREAD

**Issue by MatthewPatience** [daniel-hall/Stylish#25]
This happened all of a sudden, everything was working fine before. All of the components in the storyboard are now red (which I'm used to seeing when it can't find the style). The project doesn't appear to have any errors and I've tried trimming down the styles file to rule out any errors in it, but nothing works. Is there any way to debug why this may be happening?

I should note that when I run the application it shows all the styles just fine. If I start a fresh project or open the Stylish example project, the storyboards display styles just fine.

**Comment by daniel-hall** [comment]
Hi Matthew — thanks for reporting this issue!  My initial suggestion is to see if this is just an intermittent issue with IBDesignable in Xcode (which I’ve noticed can be flaky sometimes).  Have you tried:

1. Clear derived data / clean build folder
2. Quit and restart Xcode
3. Build and run your app target
4. Go to your storyboard and select Editor -> Refresh All View

These steps will often get IBDesignable back into a good state.  If you still encounter the same issue after those steps, it is usually due to the stylesheet not being loaded during the IBDesignable phase, perhaps because of missing the prepareForInterfaceBuilder() extensions on UIView & StyleableUIView/Label/Button shown in the sample project, or an issue locating or loading the stylesheet.json.

Let me know if none of these ideas resolve your issue or if you have any follow up questions!

**Comment by MatthewPatience** [comment]
OK, this ended up being my own issue, but it's great knowledge for others. I had a private framework that I had only compiled for ARM devices, not a universal framework that included x86 for simulators. 

I assume that for some reason Interface Builder requires your project to compile fully for simulator to be able to properly render Stylish styles.

**Comment by daniel-hall** [comment]
Ah yes!  Storyboard previews are rendered in the simulator under the hood.  Thanks for sharing the resolution.
