### ISSUE TITLE
Extending PropertyType

### ISSUE THREAD

**Issue by pgawlowski** [daniel-hall/Stylish#7]
Let's assume I want to handle myself UITextField - which is sadly not covered in stylish (BTW why?)

I've created UITextFieldPropertySet, StyleableUITextField etc. 
However UITextField contains additional properties like `UITextAutocapitalizationType`. How can I extend `JSONStyleProperty` to handle this kind of property? Am I able to handle custom properties somehow?

I can also prepare PR with 'StyleableUITextField' to extend Stylish :)

**Comment by daniel-hall** [comment]
@pgawlowski There's no good reason why UITextField isn't supported out of the box, just haven't gotten to it yet   :)

As Stylish exists currently, `JSONStyleProperty` is an enum, as you've noticed, meaning that currently the only way to add new kinds of JSON property types is by modifying the enum in your project's copy of Stylish.swift.  This really doesn't lend itself well to being extended.  

For the next iteration of Stylish, I'd like to convert the enum to be more of a factory or a mapping of the property type string from the json to the actual concrete type in Swift. And to allow extension by having client code register additional / custom json property types. One factor that will need to be considered is that the client code "extensions" have to be registered and available without the full app running, so that when Interface Builder runs the style preview by just rendering the individual views, those extensions will be applied. 

Meanwhile, all PRs (particularly building out support for `StyleableUITextField`!) are very welcome.  I appreciate your contribution and the very on-point issue above.  

I'm going to leave this issue open until Stylish supports client-extendable `JSONStyleProperty` (hopefully not long)

**Comment by pgawlowski** [comment]
Ok, for the purpose of my current project I'll (or someone from our team) introduce `StyleableUITextField` in current convention and prepare PR with this. This will allow us to keep the code integration with Stylish versioning.

We're planning to use Stylish quite widely in our demos that's why I'm thinking about some sort of script to generate `.json` file based on XML. Sadly I don't have experience in such work. Maybe you've got idea how to start with?

Another issue I've noticed - Xcode use to have problems with rendering in interface or it takes quite time especially in bigger projects. Do you have any hints or clues how to speed up this process? Is it typically xcode designables and interface builder issues or maybe we can try to better handle it on stylish side?

**Comment by daniel-hall** [comment]
That sounds great!

Regarding time to render:  I have seen some correlation between the number of IBDesignable objects to render and the render time on the storyboard. However, this has never seemed to me to be a particularly significant bottleneck.  The most significant bottleneck is how long it takes for the Swift compiler to compile your project. When you first open a storyboard, or trigger a full refresh of all designable views, IB actually compiles your entire project in the background, and then updates the views based on your IBDesignable code. So the things that would help your entire project compile faster (enabling the report on what methods are taking a long time to compile to track down bottlenecks, adding type notations where inference is taking a long time, etc.) would also make IBDesignables render faster.  

Another smaller bottleneck could be if Stylish is reloading and reparsing your style JSON to often for the different views on the screen.  To avoid this, by default, Stylish caches the JSON styles for I think 3 seconds.  Basically, so that the same load and parse pass that was used for the first view is used for all the other views on the screen.  You could always play with that constant and see if extending the cache time helps.  The tradeoff is that longer caching times means that changes you make to the JSON are less and less "real time" in how they are reflected on the storyboard.

Regarding the script to generate .json styles from XML, I've written tools to read and write JSON and XML before, but I'm not sure if that's exactly what you mean.  It seems like maybe a command line Swift utility that reads in XML, creates a Dictionary based on the parameters or values you read in from XML, and then uses JSONSerialization to write that Dictionary out to a json file might be a generally workable approach... I'm happy to share any ideas if you want to send me an email with more details of what your requirements are!

**Comment by daniel-hall** [comment]
@pgawlowski Adding custom JSONStyleProperties is now possible in the latest release!  Call Stylish.registerCustomJSONStyleProperties() and pass in an array of JSONStyleProperty instances you want to register.  Each JSON Style Property consists of an array of type names you want it to match in the JSON, and a parse closure which creates the correct kind of native swift object from the property dictionary.  Thanks for opening the issue!
