### ISSUE TITLE
Update the mechanism for registering custom style property sets and shared styles for JSON stylesheets to use extensions instead of subclassing

### ISSUE THREAD

**Issue by daniel-hall** [daniel-hall/Stylish#9]
Currently, in order to use custom style properties and components in JSON, the app needs to subclass JSONStylesheet and register the custom property sets.

To avoid inheritance and be a little more Swift-y, let's change this mechanism to be having the app add an extension to JSONStylesheet with the custom property sets to register.

**Comment by pgawlowski** [comment]
@daniel-hall - https://github.com/pgawlowski/Stylish-2 
Recently I've done in-depth rework of stylish. However I'm still trying to handle multiple issues. 
Right now repo is not very well documented :D I'm facing the problems with IBDesignables which are not rendering since I'm installing Stylish-2 as pods. In normal usage it seems to work fine. 

Feel free to comment - every single feedback will be precious for our team.

**Comment by daniel-hall** [comment]
@pgawlowski With the changes that have just been made to turn Stylish into a linked framework target, you may find some helpful ideas for making it work as a pod. One of the main difficulties with IBDesignable is finding a way to register things like shared style classes, custom property sets, etc. _before_ the storyboard IBDesignable render pass. IBDesignable never actually runs the app or the app delegate, so it's tricky to find an entry point for setting up global state in time for storyboard previews. 

You can see how this is addressed in the updated StylishExample project.  There is an extension override for UIView.prepareForInterfaceBuilder that handles all global registrations in one place, which gets everything working for IBDesignable. For the normal app execution path, those same registrations are made in the app delegate when the app starts up.
